# For more information: https://laravel.com/docs/sail
version: '3'
services:
  laravel:
    image: yourpoke/laravel:latest
    container_name: yourpoke_laravel
    restart: on-failure:5
    volumes:
      - ./laravel:/var/www/laravel
    networks:
      - yourpoke-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.29
    command:
      [
        "mysqld",
        "--default-authentication-plugin=mysql_native_password"
      ]
    container_name: yourpoke_mysql
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-pokextremelysecurepassword}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${DB_DATABASE:-pokedb}
      MYSQL_USER: ${DB_USERNAME:-pokeuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-pokextremelysecurepassword}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - yourpoke-network

  vue:
    image: yourpoke/vue:latest
    container_name: yourpoke_vue
    restart: on-failure:5
    tty: true
    ports:
      - 6969:6969
    volumes:
      - ./vue/src:/app/src

  nginx:
    image: yourpoke/nginx:latest
    container_name: yourpoke_nginx
    restart: on-failure:5
    ports:
      - 80:80
      - 3000:3000
      - 443:443
    networks:
      - yourpoke-network
    volumes:
      - ./laravel:/var/www/laravel
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  yourpoke-network:
    driver: bridge
volumes:
  dbdata: { }
